# Generated by Django 5.2.9 on 2025-12-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='crsted_at',
            new_name='created_at',
        ),
    ]
