# Generated by Django 5.2.9 on 2025-12-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
